# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
# This example is compatible with Dynamixel using protocol 1.0
head:
  ID: 1
  Return_Delay_Time: 0
  CW_Angle_Limit: 50
  CCW_Angle_Limit: 650
  Moving_Speed: 100
left_shoulder:
  ID: 2
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Moving_Speed: 100
left_elbow:
  ID: 3
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Moving_Speed: 100
right_shoulder:
  ID: 4
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Moving_Speed: 100
right_elbow:
  ID: 5
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Moving_Speed: 100
